/*
* generated by Xtext
*/
package org.lobid.metatext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MetatextOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
