/*
 * generated by Xtext
 */
package org.lobid.metatext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MetatextRuntimeModule extends org.lobid.metatext.AbstractMetatextRuntimeModule {

}
